image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Kasik96.swift@0.1.0:Q5PBUv3yxGt0LugfEN0nsg==
    - unpublished.sourcekit-lsp@0.0.1:NJBDyUtdIfPBJcBUYsntWQ==
    
# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: 'echo "Test-Session"'
    command: swift --version
