#if !canImport(ObjectiveC)
import XCTest

extension NumberCheckerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NumberCheckerTests = [
        ("testIsNumberGreaterThanZero", testIsNumberGreaterThanZero),
        ("testIsNumberGreaterThanZeroTofail", testIsNumberGreaterThanZeroTofail),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NumberCheckerTests.__allTests__NumberCheckerTests),
    ]
}
#endif
